### PR TITLE
Update react-native-geolocation.podspec

### PR DESCRIPTION
**Pull request by WoLewicki**
# Overview

PR adding new arch compatibility for newest RN version, same PR as e.g. here: https://github.com/react-native-cameraroll/react-native-cameraroll/pull/577

# Test Plan

### CODE REVIEW

**Comment by WoLewicki** [comment]
@michalchudziak could we get this merged and released since it is needed for newest RN to work on new arch 🚀

**Comment by michalchudziak** [comment]
Hey! Sure, I'd love to merge that one, but I would like to understand how will it impact older RN version support. Could you elaborate a bit on that?

**Comment by WoLewicki** [comment]
`install_modules_dependencies` is available from RN `0.71` iirc. For older versions, you will go into `else` clause making it work as it worked before. For newer versions, it will automatically add all the needed dependencies based on if app is using old or new arch. You can see some more info here: https://github.com/react-native-webview/react-native-webview/pull/3231 with a comment from Meta member 🚀

**Review by michalchudziak — APPROVED** [review]

**Comment by WoLewicki** [comment]
Could we get a quick release with this change?

**Pull request merged**
